### ISSUE TITLE
No new release in the past year

### ISSUE THREAD

**Issue by vanschelven** [Yelp/swagger_spec_validator#128]
Even though some PRs have been merged, no release has been made in the past year or so.

This means (probably among other things) that the last released version has failing tests.

**Comment by macisamuele** [comment]
@vanschelven that's a fair point.

Checking the un-released changes only #122 seems having impact on the library, all the other PRs were related to internal testing.

Still #122 is pretty interesting due to the speed improvements that it could provide, so I'll try to release this package in the next days.

**Comment by macisamuele** [comment]
Version 2.5.0 was just released 🎉 

Closing this

**Comment by vanschelven** [comment]
👍
