### ISSUE TITLE
Latest Version Missing on PyPI

### ISSUE THREAD

**Issue by ivan-c** [Yelp/swagger_spec_validator#59]
The latest version (2.0.3) [appears to be missing on PyPI](https://pypi.python.org/simple/swagger-spec-validator/).

Could someone upload version 2.0.3?

Thanks!

**Comment by dimbleby** [comment]
Duplicates #50, I think, which asks for the same thing.

**Comment by dimbleby** [comment]
No, my mistake - I see that 2.0.3 has sort-of been released (yay!) and this issue says that something has gone wrong with that process.

**Comment by YuvalAdler** [comment]
I'm having the same issue (output of pyp2rpm):
> Package "swagger_spec_validator" could not be found on PyPI.

and

> swagger-spec-validator package has no sources on PyPI, Please ask the maintainer to upload sources.

**Comment by code-ape** [comment]
Can someone please post on the status of this? The release of 2.0.3 occurred in November 2016 and, as of today in February 2017, the most recent version that one can install from PyPi is 2.0.2. The release of 2.0.3 solves the major issue of correctly validating declarations of returning files from API calls. Many other python projects (such as Connexion, the reason I've tracked this issue down) need this update to be able to support specs properly.

For the record PyPi has 2.0.3 declared ([link](https://pypi.python.org/pypi/swagger-spec-validator)) but there isn't an actual package with it. Thus 2.0.2 is installed since it is the last one with an actual package loaded ([link](https://pypi.python.org/pypi/swagger-spec-validator/2.0.2)).

Cheers and thanks for your help,
code-ape

**Comment by code-ape** [comment]
@sjaensch Thank you :)
